### ISSUE TITLE
Ram configuration issue

### ISSUE THREAD

**Issue by TheDemonicStaff-t** [North-West-Wind/CurseForge-CLI#10]
Whenever I attempt to edit the modpack profile to set ram use, it gives me an error saying it cannot edit the profile.  The modpacks are essentially unplayable without more ram.

**Comment by North-West-Wind** [comment]
This is due to the faulty profile generation after installing a modpack. You can change the configuration by directly editing `launcher_profiles.json` in your `.minecraft` directory for now.

**Comment by North-West-Wind** [comment]
This is fixed in v1.3.8. However, old installations still have this problem. You can fix them by copying `"1970-01-01T00:00:00.000Z"` to `"created": ` and `"lastUsed": ` of the profile(s) in `launcher_profiles.json`
