### ISSUE TITLE
unable to collect mod files from curse

### ISSUE THREAD

**Issue by USMP-lancer** [North-West-Wind/CurseForge-CLI#11]
java.io.IOException: Server returned HTTP response code: 503 for URL: https://northwestwind.ml/api/curseforge/mods/285109
idk if this is a termux issue or because of the api changes

**Comment by North-West-Wind** [comment]
This is just an issue from my end. It happens when my API crashes. Not-fixable from this program unfortunately, but I can fix the API.

If you have this problem in the future, just try again later.
