### ISSUE TITLE
How to Run Modpacks?

### ISSUE THREAD

**Issue by SFNDude123502** [North-West-Wind/CurseForge-CLI#14]
i know this is a really stupid issue, but i have no clue on how to run these modpacks once they are downloaded

**Comment by North-West-Wind** [comment]
This program is designed to use the vanilla Minecraft launcher. After installing, you should see a profile in installations in the Minecraft launcher. It's common that the mod launcher is not found, so you will have to install it yourself and edit the profile to use the mod launcher you installed.
