### ISSUE TITLE
Commands don't respond, again

### ISSUE THREAD

**Issue by TheGamerInDisguise** [North-West-Wind/CurseForge-CLI#20]
This was fixed as someone pointed out, but this issue has been arising with me again
Whenever I type a command, it simply responds with 
CurseForge CLI 1.4.1
After that, it goes blank

**Comment by North-West-Wind** [comment]
For example?

**Comment by Kai-Pendleton** [comment]
Hello, I am having this problem as well.
For example, I entered the command "./curseforge install 655739" to install ATM7 - To the Sky, but all that returned was a single line "CurseForgeCLI v1.4.1"
Afterwards, the program returned.

**Comment by marelct** [comment]
I had the same problem, you just have to write ./curseforge modpack install instead of ./curseforge install

**Comment by Kai-Pendleton** [comment]
> I had the same problem, you just have to write ./curseforge modpack install instead of ./curseforge install

This solved it! What a silly mistake.
Thanks!
