### ISSUE TITLE
Installing modpack returns error.

### ISSUE THREAD

**Issue by Perisys1312** [North-West-Wind/CurseForge-CLI#9]
I'm on Arch Linux and every time I attempt to install this modpack, it returns this error.

![2022-06-24-14:34:14-screenshot](https://user-images.githubusercontent.com/79767842/175655701-5b86e54a-af9c-48f8-ad1a-9916d5fe4457.png)

**Comment by North-West-Wind** [comment]
Fixed with v1.3.3
